spring.application.name=yachay

spring.datasource.url=jdbc:mysql://localhost:3306/yachay_db?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:mysql}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
